.PHONY: lint
lint:
	@echo "Running linters... 🔄"
	ruff check --fix
	ty check
	pre-commit install
	pre-commit run -a
	@echo "Linters completed. ✅"

{% if database.value == "PostgreSQL" or database.value == "MySQL" or has_store %}
INFRA_COMPOSE_FILE := docker-compose.infra.yml

.PHONY: start-infra
start-infra:
	@echo "Starting infrastructure... 🔄"
	docker compose -f $(INFRA_COMPOSE_FILE) up -d
	@echo "Infrastructure started. ✅"

.PHONY: stop-infra
stop-infra:
	@echo "Stopping infrastructure... 🔄"
	docker compose -f $(INFRA_COMPOSE_FILE) down
	@echo "Infrastructure stopped. ✅"
{% endif %}

{% if docker %}
.PHONY: start
start:
	@echo "Starting application with Docker... 🔄"
	docker compose up -d
	@echo "Application started. ✅"

.PHONY: stop
stop:
	@echo "Stopping application with Docker... 🔄
	docker compose down
	@echo "Application stopped. ✅"
{% endif %}
