.PHONY: lint
lint:
	@echo "Running linters... 🔄"
	ruff check --fix
	ty check
	pre-commit install
	pre-commit run -a
	@echo "Linters completed. ✅"

{% if database.value == "PostgreSQL" or database.value == "MySQL" or has_store %}
DEV_INFRA_COMPOSE_FILE := docker-compose.dev-infra.yml

.PHONY: start-dev-infra
start-dev-infra:
	@echo "Starting dev infrastructure... 🔄"
	docker compose -f $(DEV_INFRA_COMPOSE_FILE) up -d
	@echo "Dev infrastructure started. ✅"

.PHONY: stop-dev-infra
stop-dev-infra:
	@echo "Stopping dev infrastructure... 🔄"
	docker compose -f $(DEV_INFRA_COMPOSE_FILE) down
	@echo "Dev infrastructure stopped. ✅"
{% endif %}

{% if docker %}
.PHONY: start
start:
	@echo "Starting application with Docker... 🔄"
	docker compose up -d
	@echo "Application started. ✅"

.PHONY: stop
stop:
	@echo "Stopping application with Docker... 🔄
	docker compose down
	@echo "Application stopped. ✅"
{% endif %}
